### PR TITLE
Remove uglifyjs `--wrap` option to fix strict-mode

### PR DESCRIPTION
**Pull request by eirikurn**
The library crashed in our environment which has [Strict Mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) enabled due to this code generated by uglifyjs:

```
i = function() {
  return this
}(),
i[""] = {}
```

In normal mode `i` is `window` or `global`. In strict mode, `i` is `undefined` which causes an error in the last line.

As the library is written right now, `--wrap` is not providing any value since all of the code is already wrapped, so it should be a 100% backwards compatible change.

### CODE REVIEW

**Comment by HermannBjorgvin** [comment]
I'll add this to the list of things for the next version. I'm currently adding support for the new type of national id's as well.

If this is blocking you I recommend using [patch-package](https://www.npmjs.com/package/patch-package) which lets you apply a local patch which you can commit and can be removed when the next update drops.

**Comment by eirikurn** [comment]
Thanks Hermann. This was blocking us, but we've found some workaround and will consider patch-package.

**Comment by HermannBjorgvin** [comment]
@eirikurn I pushed a v2.0.0 branch/tag. There is a small addition to the API for temporary id's but it also removes the redundant wrap. The code needs to be refactored since the addition of temporary id's has made the code pretty ugly in places.

You can install v2.0.0 using yarn: `yarn add "https://github.com/hermannbjorgvin/kennitala.git#2.0.0"`. I'll also publish a beta package for v2 before releasing it so people can test and suggest improvements since temporary id's require some breaking changes. If you have any ideas for improvement that would be appreciated.

BTW see about the new temporary id's that will be considered valid in 2.0.0
https://www.skra.is/folk/eg-i-thjodskra/um-kennitolur/um-kerfiskennitolur/

Some parts of the API such as .info won't work for temporary id's since they don't include that personal information.

Temporary id's do mean that national id's do lose some use cases since you can't rely on them having a valid date included. So you might need to change whatever logic to adjust to that if that's one of your use cases.

**Comment by eirikurn** [comment]
Awesome job. Thanks!

**Comment by eirikurn** [comment]
Our security policy does not allow us to depend on a git branch/tag. Can you publish the beta to NPM instead?

https://kevinkreuzer.medium.com/publishing-a-beta-or-alpha-version-to-npm-46035b630dd7

**Comment by HermannBjorgvin** [comment]
@eirikurn version [2.0.0-beta.0](https://www.npmjs.com/package/kennitala/v/2.0.0-beta.0) is out now. Sorry for the delay, had some problem with my NPM account.

**Comment by HermannBjorgvin** [comment]
Closing since these changes along with a few other were implemented in the V2.0.0 branch. Thanks for the contribution!

**Pull request closed without merging**
